#!/bin/bash

############################################################################
## Used to create virtual uart ports in /dev/pty and link them to two files

USERPORT=$RVATOM/userport
SIMPORT=$RVATOM/simport

if [[ $1 == -v ]]
then
    echo "sim port : $SIMPORT"
    echo "user port: $USERPORT"

    echo -n "Generating Virtual UART Ports... "
fi

socat pty,link=$USERPORT,echo=0 pty,link=$SIMPORT,echo=0 &

if [[ $1 == -v ]]
then
    echo " Done!"
fi