#!/bin/bash

############################################################################
## Used to create virtual uart ports in /dev/pty and link them to two files
# silence this script using '-s' flag

USERPORT=$RVATOM/userport
SIMPORT=$RVATOM/simport

if [[ $1 != -s ]]
then
    echo "simport : $SIMPORT"
    echo "userport: $USERPORT"

    echo -n "Generating Virtual UART Ports... "
fi

socat pty,link=$USERPORT,echo=0 pty,link=$SIMPORT,echo=0 &

if [[ $1 != -s ]]
then
    echo " Done!"
fi