#!/bin/bash
# set -x # display execution trace

#------------------- BASH COLORS ------------------
RED="\e[31m"
GREEN="\e[32m"
ORANGE="\e[33m"

NOCOLOR="\e[0m"
#--------------------------------------------------
# Detect atomsim target
detectedtarget=$(atomsim --simtarget)
echo -e "${ORANGE}Detected atomsim target: $detectedtarget ${NOCOLOR}"

# Detect current directory
currdir=$(pwd)
echo -e "${ORANGE}current directory: $currdir ${NOCOLOR}"

exampledir=$RVATOM/sw/examples/

cd ${exampledir}

#---------------------------------------------------
for dir in $RVATOM/sw/examples/*/     # list directories in the form "/tmp/dirname/"
do
    dir=${dir%*/}      # remove the trailing "/"

    # print everything after the final "/"
    echo -e "------------------ Running Example: ${dir##*/} ------------------"
 
    make ex=${dir##*/} target=${detectedtarget} run
done

cd ${currdir}