TARGET_SIM ?= atomsim
ifeq ($(shell command -v $(TARGET_SIM) 2> /dev/null),)
    $(error Target simulator executable '$(TARGET_SIM)` not found)
endif

RUN_TARGET= $(TARGET_SIM) --maxitr=100000000 --signature=$(*).signature.output $(<) 2> $@
#RUN_TARGET= echo "$(TARGET_SIM) --maxitr=100000000 --signature=$(*).signature.output $(<) 2> $@"

RISCV_PREFIX   ?= riscv64-unknown-elf-
RISCV_GCC      ?= $(RISCV_PREFIX)gcc
RISCV_OBJCOPY  ?= $(RISCV_PREFIX)objcopy
RISCV_OBJDUMP  ?= $(RISCV_PREFIX)objdump
RISCV_GCC_OPTS ?= -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -march=rv32i -mabi=ilp32

COMPILE_TARGET=\
	$$(RISCV_GCC) $(1) $$(RISCV_GCC_OPTS) \
		-I$(ROOTDIR)/riscv-test-env/ \
		-I$(TARGETDIR)/$(RISCV_TARGET)/ \
		-T$(TARGETDIR)/$(RISCV_TARGET)/link.ld $$< \
		-o $$@; \
	$$(RISCV_OBJDUMP) -D $$@ > $$@.objdump; \